sudo: required
language: go
go:
- 1.12.x
services:
- docker
jobs:
  include:
  - name: tests
    os: linux
    cache:
      directories:
      - $GOPATH/pkg/mod
    install:
    |
      go mod download
      go get github.com/rakyll/statik
      go generate ./generate.go
      export PACK_PATH="$PWD/artifacts/pack-${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}-${TRAVIS_OS_NAME}"
      if [[ $TRAVIS_OS_NAME = linux ]]; then export CGO_ENABLED=0; fi
      go build -ldflags "-X 'main.Version=$TRAVIS_TAG (git sha: $(git log -1 --pretty=%H))'" -o "$PACK_PATH" ./cmd/pack
      "$PACK_PATH" version
    script:
    |
      ./remove-lifecycle/script.sh
      export PACK_TAG=nolifecycle
      go test -count=1 -parallel=1 -v -tags=acceptance ./acceptance
